sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - node
branches:
  only:
    - master
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
after_success:
  - npm publish
notifications:
  email:
    recipients:
    - devtonirm@gmail.com
    on_success: change
    on_failure: always